# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a higher heap size (2048 MB) to prevent GC thrashing.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use this property to specify which project-specific cache to use.
# org.gradle.caching=true

# Enables parallel execution of tasks.
org.gradle.parallel=true

# AndroidX libraries use this property to enable features like Jetifier.
android.useAndroidX=true
android.nonTransitiveRClass=true
